# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "warbird-lifter"

[variables]
CMAKE_MODULE_PATH = "${CMAKE_SOURCE_DIR}/cmake"
GFLAGS_USE_TARGET_NAMESPACE = true

[find-package.LLVM-Wrapper]
[find-package.remill]
[find-package.fmt]

[target.warbird-lifter]
type = "executable"
compile-features = ["cxx_std_23"]
sources = ["src/**.cpp"]
headers = ["src/**.hpp"]
private-compile-options = ["-Wno-invalid-offsetof"]
private-include-directories = ["src/"]
link-libraries = ["::LLVM-Wrapper", "::remill", "fmt"]

[subdir.intrinsics]